### ISSUE TITLE
Incompatible with farmer's delight refabricated

### ISSUE THREAD

**Issue by amogus8** [vlad250906/Create-UfoPort#3]
Error:

Uncaught exception in thread "main"
java.lang.RuntimeException: Non-unique Mixin config name porting_lib_accessors.mixins.json used by the mods porting_lib and porting_lib_accessors
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:91)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

if i try to start minecraft with farmer's delight refabricated and create port i have this error
seems like porting libs from create port and farmer's delight refabricated are incompatible
version: fabric 1 21 1 create port version: 0-9-3-b Farmer's delight refabricated version: 2.2.7
fabric version: 0.16.9
[latest.log](https://github.com/user-attachments/files/18053580/latest.log)

**Comment by vlad250906** [comment]
The official version of Porting Lib is raw and buggy as hell. The simple <new FluidTank()> can completely crash the game with porting-lib-1.21. I tried renaming my fork of Porting Lib (to porting_lib_ufo), but incompatibility is still remains. Will I fixe it sometime? Idk.

**Comment by amogus8** [comment]
UPDATE!!!!! there is new update of farmer's delight refabricated where they cut off porting lib!!! and now create ufoport and porting lib work together!!!

![Image](https://github.com/user-attachments/assets/ed7e6964-7ced-44c2-b5d9-efb85521ee61)

**Comment by amogus8** [comment]
use farmer's delight refabricated 3.0.0+ to play with create ufoport!
